<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:intel-esg="http://www.intel.com/soae/localServices/REST/" xmlns:md="http://www.intel.com/soae/protocolMetadata-2007a.xsd" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:tns="http://www.example.com/Test/restconfig" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="RestConfig" targetNamespace="http://www.example.com/Test/restconfig">
  <wsdl:message name="RestConfigRequest">
    <wsdl:part name="appname" type="xsd:string"/>
    <wsdl:part name="filename" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="RestConfigResponse">
    <wsdl:part name="body" type="xsd:anyType"/>
  </wsdl:message>
  <wsdl:portType name="RestConfig">
    <wsdl:operation name="">
      <wsdl:input message="tns:RestConfigRequest"/>
      <wsdl:output message="tns:RestConfigResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="RestConfigBinding" type="tns:RestConfig">
    <http:binding verb="GET"/>
    <wsdl:operation name="">
      <http:operation/>
      <wsdl:input>
        <http:urlEncoded intel-esg:optional="appname filename"/>
        <intel-esg:parameterMapping>
          <intel-esg:mapEntry name="appname" part="appname"/>
          <intel-esg:mapEntry name="filename" part="filename"/>
        </intel-esg:parameterMapping>
      </wsdl:input>
      <wsdl:output>
        <mime:content part="body" type="text/xml"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="RestConfigService">
    <wsdl:port binding="tns:RestConfigBinding" name="RestConfigPort">
      <http:address location="http://localhost:9997"/>
    </wsdl:port>
  </wsdl:service>
  <plnk:partnerLinkType name="RestConfigPartnerLinkType">
    <plnk:role name="service" portType="tns:RestConfig"/>
  </plnk:partnerLinkType>
</wsdl:definitions>